# Generated by Django 3.1 on 2020-08-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
