# Generated by Django 3.1 on 2020-08-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previousorders',
            name='plants',
        ),
        migrations.AddField(
            model_name='previousorders',
            name='orders',
            field=models.ManyToManyField(to='orders.Order'),
        ),
    ]
